### ISSUE TITLE
No user in database, API says there is

### ISSUE THREAD

**Issue by derfWayne** [shafiquejamal/play-authentication#2]
@shafiquejamal 

When navigating to http://localhost:9000/email/user_email, the api returns a value of true. However, the user that is being queried does not exists anywhere in the database.

Same goes with http://localhost:9000/username/username.

<img width="1224" alt="screen shot 2017-02-27 at 6 02 36 pm" src="https://cloud.githubusercontent.com/assets/11152179/23385690/283cc4c0-fd17-11e6-8447-2c46d08ca819.png">

<img width="659" alt="screen shot 2017-02-27 at 6 02 43 pm" src="https://cloud.githubusercontent.com/assets/11152179/23385689/283c874e-fd17-11e6-9f26-024c939d06f6.png">

<img width="1182" alt="screen shot 2017-02-27 at 6 31 29 pm" src="https://cloud.githubusercontent.com/assets/11152179/23386313/4fa1ed20-fd1b-11e6-8f05-2a535ccd8db4.png">

<img width="1024" alt="screen shot 2017-02-27 at 6 32 08 pm" src="https://cloud.githubusercontent.com/assets/11152179/23386314/4fb04dac-fd1b-11e6-97f1-d9b1a412685f.png">

**Comment by shafiquejamal** [comment]
Hello,

If I recall correctly, the value of "true" answers the question "Is this email address available for registering?", meaning "Can someone register a new account using this email address?". The answer is yes/true if the email address is NOT already in the DB. 

So when that email address is in the DB, then the result should read "false".

(Also, I suggest URL encoding the email address, so that "@" becomes "%40").

Please let me know whether this response addresses the issue. Thanks.

**Comment by derfWayne** [comment]
@shafiquejamal

I shared a dropbox link with you via email. It contains screen recordings of the test I conducted that shows the registration failing with email already registered. 

It also has watch variables from the registration code. If you observe you will see the response object stays undefined. I'm currently diving into why it is not being updated however, if you can offer some further insight as to what may be causing this I can move along to the next thing.

**Comment by shafiquejamal** [comment]
Hello, thanks for letting me know about this. Sorry for the delay. I won't be able to look at this this week, though from my brief viewing of the videos you sent me, it seems you might be passing undefined arguments to some functions. I'll have another look on the weekend.

**Comment by derfWayne** [comment]
Hello @shafiquejamal were you able to take a gander at the above issue. Unsure of how undefined arguments are being passed. I have yet to make any code modifications at all. Please advise if you were able to replicate the issue and if you've developed a solution.

**Comment by derfWayne** [comment]
@shafiquejamal  In diving into the code more. I see that there is a disconnect between the UI and the backend. WHen I make a direct call to the backend like http://localhost:9000/email/email@address.com it works and I see that my breaks are in tact. However, standing the app up and initiating calls from UI the backend is never called. I'm diving deeper into this now.

**Comment by derfWayne** [comment]
Erroneous characters in LoginRegister.jsx. Removed and all is working with no issues. Thanks for all your assistance @shafiquejamal .

**Comment by shafiquejamal** [comment]
Hello, sorry about not getting to this sooner. When you get a chance, can you send or issue a PR changes to the code to LoginRegister.jsx file, so that the changes can be reflected in the repo? Thanks.
